name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    uses: apartmentlist/github-actions/.github/workflows/pr-agent.yml@main
    secrets: inherit
